# Generated by Django 4.0.1 on 2022-01-20 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_post_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.locality'),
        ),
    ]
