# Generated by Django 4.0.1 on 2022-01-28 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='range_meters',
            field=models.PositiveBigIntegerField(default=10000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(80000)]),
        ),
    ]
