# Generated by Django 4.0.1 on 2022-01-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_range_meters'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extend_to_locality',
            field=models.BooleanField(default=False),
        ),
    ]
