# Generated by Django 4.0.1 on 2022-02-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_post_extend_to_locality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
