# Generated by Django 4.0.1 on 2022-02-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
