# Generated by Django 4.0.1 on 2022-02-18 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_post_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='range_meters',
            field=models.PositiveBigIntegerField(default=5000, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
