# Generated by Django 4.0.1 on 2022-02-22 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_post_content_alter_post_range_meters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('delete_hash', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=6000),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.image'),
        ),
    ]
