# Generated by Django 4.0.1 on 2022-03-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_image_alter_post_title_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
